# Generated by Django 5.2.5 on 2026-08-28 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('superadmin', 'Super administrator'), ('director', 'Executive director'), ('country_director', 'Country director'), ('programme_manager', 'Programme manager'), ('mentorship_coordinator', 'Mentorship coordinator'), ('science_fair_coordinator', 'Science Fair coordinator'), ('content_editor', 'Content editor'), ('finance', 'Finance'), ('viewer', 'Viewer')], db_index=True, default='viewer', max_length=40)),
                ('country', models.CharField(blank=True, choices=[('', 'All countries'), ('UG', 'Uganda'), ('SS', 'South Sudan')], default='', help_text='Leave blank for access across all countries.', max_length=2)),
                ('position', models.CharField(blank=True, help_text='Job title, as they would write it.', max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff profile',
                'ordering': ['user__username'],
            },
        ),
    ]
