# Generated by Django 5.2.5 on 2026-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permissionoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'All countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], default='', help_text='Leave blank for access across all countries.', max_length=2),
        ),
    ]
