# Generated by Django 5.2.5 on 2026-08-29 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_staffprofile_country'),
        ('content_cms', '0004_programme_pageblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='team_member',
            field=models.ForeignKey(blank=True, help_text='Left blank, the matching team member is found by email, then by name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_accounts', to='content_cms.teammember'),
        ),
    ]
