# Generated by Django 5.2.5 on 2026-08-30 07:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0008_boardcolumn_is_hidden_alter_boardcolumn_show_in_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, help_text='Made automatically if left blank.', max_length=20, unique=True)),
                ('student_name', models.CharField(db_index=True, max_length=200)),
                ('photo', models.CharField(blank=True, help_text='A photograph of the student.', max_length=500)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Prefer not to say')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('student_phone', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[\\d\\s()-]{6,20}$')])),
                ('school_name', models.CharField(db_index=True, max_length=200)),
                ('school_level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('vocational', 'Vocational / technical'), ('tertiary', 'University / tertiary')], db_index=True, default='secondary', max_length=20)),
                ('school_contact', models.CharField(blank=True, help_text='Bursar or head teacher, and how to reach them.', max_length=200)),
                ('school_account', models.CharField(blank=True, help_text='Where fees are paid. Kept so a transfer can be checked against it.', max_length=200)),
                ('class_at_award', models.CharField(blank=True, help_text='The class they were in when the bursary started, e.g. S2.', max_length=60)),
                ('current_class', models.CharField(blank=True, max_length=60)),
                ('sponsor_name', models.CharField(blank=True, db_index=True, help_text='Who is paying for this student.', max_length=200)),
                ('sponsor_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('organisation', 'Organisation'), ('church', 'Church or faith group'), ('foundation', 'Trust or foundation'), ('jdiobe', 'JdiobeSTEM general fund'), ('other', 'Other')], max_length=20)),
                ('sponsor_contact', models.CharField(blank=True, max_length=200)),
                ('amount_per_term', models.DecimalField(blank=True, decimal_places=2, help_text='What the bursary covers each term, before any extras.', max_digits=12, null=True)),
                ('total_committed', models.DecimalField(blank=True, decimal_places=2, help_text='The whole commitment, if one was agreed up front.', max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, help_text='e.g. UGX, SSP, USD.', max_length=8)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('expected_end_on', models.DateField(blank=True, help_text='When the bursary is expected to finish.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending start'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=20)),
                ('ended_on', models.DateField(blank=True, help_text='When it actually ended, whether completed or stopped.', null=True)),
                ('termination_reason', models.TextField(blank=True, help_text='Why it ended. Required in practice whenever it ended early.')),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, help_text='Mother, father, aunt, grandparent…', max_length=60)),
                ('guardian_phone', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[\\d\\s()-]{6,20}$')])),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_occupation', models.CharField(blank=True, max_length=120)),
                ('guardian_address', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
                ('managed_by', models.ForeignKey(blank=True, help_text='Who at the Foundation looks after this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='operations.office')),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='e.g. Scholastic materials.', max_length=120)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_on', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('term', models.CharField(blank=True, help_text='What the payment covers, e.g. Term 1 2026.', max_length=60)),
                ('academic_year', models.CharField(blank=True, help_text='e.g. 2026.', max_length=20)),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('mobile', 'Mobile money'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Bank or mobile money reference.', max_length=120)),
                ('receipt', models.CharField(blank=True, help_text="The school's receipt for this payment.", max_length=500)),
                ('paid_to', models.CharField(blank=True, help_text="Who received it, if not the school's usual account.", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_payments', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
    ]
