# Generated by Django 5.2.5 on 2026-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='guardian_occupation',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='reference',
            field=models.CharField(blank=True, editable=False, help_text='Issued automatically when the bursary is created.', max_length=20, unique=True),
        ),
    ]
