# Generated by Django 5.2.5 on 2026-09-14 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_payment_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshippayment',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='The colleague who actually sent it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_payments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
