# Generated by Django 5.2.5 on 2026-09-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0009_scholarshippayment_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='combination',
            field=models.CharField(blank=True, help_text='A-level subject combination, e.g. PCM. S5 and S6 only.', max_length=60),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='course',
            field=models.CharField(blank=True, help_text='What they are studying, at a university or technical institute.', max_length=200),
        ),
    ]
