# Generated by Django 5.2.5 on 2026-08-28 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monday_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('fundraising', 'Fundraising'), ('finance', 'Finance'), ('programmes', 'Programmes'), ('people', 'People & HR'), ('governance', 'Governance & compliance'), ('operations', 'Operations'), ('marketing', 'Marketing & events'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('is_subitem_board', models.BooleanField(db_index=True, default=False)),
                ('is_visible', models.BooleanField(default=True, help_text='Uncheck to hide from the dashboard without deleting anything.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('parent_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subitem_boards', to='operations.board')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('column_type', models.CharField(db_index=True, max_length=40)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('show_in_list', models.BooleanField(default=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='operations.board')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('board', 'monday_id'), name='unique_column_per_board')],
            },
        ),
        migrations.CreateModel(
            name='BoardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='operations.board')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('board', 'monday_id'), name='unique_group_per_board')],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monday_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('name', models.CharField(max_length=500)),
                ('group_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('is_local', models.BooleanField(db_index=True, default=False)),
                ('monday_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='operations.board')),
                ('parent_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='operations.record')),
            ],
            options={
                'ordering': ['-monday_updated_at', '-created_at'],
                'indexes': [models.Index(fields=['board', 'group_id'], name='operations__board_i_90b9e8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('monday_id__gt', '')), fields=('board', 'monday_id'), name='unique_record_per_board')],
            },
        ),
    ]
