# Generated by Django 5.2.5 on 2026-08-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_board_country_record_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Two-letter code, matching the country stored on other records. 'GL' is reserved for Global.", max_length=2, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('currency_code', models.CharField(help_text='ISO 4217, e.g. UGX.', max_length=3)),
                ('currency_symbol', models.CharField(blank=True, max_length=8)),
                ('office', models.CharField(blank=True, help_text='Where the office is, if there is one.', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'operating country',
                'verbose_name_plural': 'operating countries',
                'ordering': ['order', 'name'],
            },
        ),
    ]
