# Generated by Django 5.2.5 on 2026-08-28 10:28

import django.db.models.deletion
from django.db import migrations, models


def carry_offices_across(apps, schema_editor):
    """Turn each country's office text into its main Office row."""
    Country = apps.get_model('operations', 'OperatingCountry')
    Office = apps.get_model('operations', 'Office')
    for country in Country.objects.all():
        text = (getattr(country, 'office', '') or '').strip()
        if not text:
            continue
        Office.objects.create(
            country=country,
            name=f'{country.name} country office',
            is_main=True,
            city=text,
            order=0,
        )


def undo(apps, schema_editor):
    apps.get_model('operations', 'Office').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_operatingcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_main', models.BooleanField(db_index=True, default=False, help_text="The country's principal office. Only one per country.")),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='operations.operatingcountry')),
            ],
            options={
                'ordering': ['country__order', '-is_main', 'order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('country',), name='one_main_office_per_country')],
            },
        ),
        migrations.RunPython(carry_offices_across, undo),
        migrations.RemoveField(
            model_name='operatingcountry',
            name='office',
        ),
    ]
