# Generated by Django 5.2.5 on 2026-08-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Which office this belongs to, where that is narrower than the country.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='operations.office'),
        ),
    ]
