# Generated by Django 5.2.5 on 2026-08-29 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_record_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='established_on',
            field=models.DateField(blank=True, help_text='When the office opened.', null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Who runs this office.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices_led', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='office',
            name='registration_number',
            field=models.CharField(blank=True, help_text='As registered with the authorities in this country.', max_length=120),
        ),
        migrations.AddField(
            model_name='office',
            name='staff_headcount',
            field=models.PositiveSmallIntegerField(blank=True, help_text='People based here.', null=True),
        ),
    ]
