# Generated by Django 5.2.5 on 2026-08-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_record_created_by_record_created_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='boardcolumn',
            name='show_in_list',
            field=models.BooleanField(default=True, help_text='Show this column in the table view.'),
        ),
    ]
