# Generated by Django 5.2.5 on 2026-09-11 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(db_index=True, help_text='Who billed us.', max_length=200)),
                ('number', models.CharField(blank=True, db_index=True, help_text="The supplier's own invoice number.", max_length=80)),
                ('description', models.CharField(blank=True, help_text='What it is for.', max_length=300)),
                ('issued_on', models.DateField(db_index=True, help_text='The date on the invoice.')),
                ('due_on', models.DateField(blank=True, db_index=True, help_text='When it has to be paid by.', null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(blank=True, help_text='e.g. UGX.', max_length=8)),
                ('status', models.CharField(choices=[('received', 'Received'), ('approved', 'Approved for payment'), ('queried', 'Queried'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20)),
                ('paid_on', models.DateField(blank=True, help_text='Left empty, the invoice counts as outstanding.', null=True)),
                ('document', models.URLField(blank=True, help_text='The invoice itself.', max_length=500)),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('expense', models.ForeignKey(blank=True, help_text='The expense that settled it, once it has been paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='operations.record')),
                ('office', models.ForeignKey(blank=True, help_text='Which office it belongs to, where that is narrower than the country.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='operations.office')),
            ],
            options={
                'ordering': ['-issued_on', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('number__gt', '')), fields=('supplier', 'number'), name='unique_invoice_per_supplier')],
            },
        ),
    ]
