# Generated by Django 5.2.5 on 2026-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('fundraising', 'Fundraising'), ('finance', 'Finance'), ('programmes', 'Programmes'), ('people', 'People & HR'), ('governance', 'Compliance & offices'), ('operations', 'Operations'), ('marketing', 'Marketing & events'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
