"""
Load the editable copy for the hand-built pages.

Every value is lifted verbatim from the page it came from, so seeding changes
where the words are read from and not what they say. Each page component still
carries the same text as a fallback, which is why a block can be unpublished or
deleted without leaving a hole.
"""

from django.core.management.base import BaseCommand

from content_cms.models import PageBlock

#: page -> [(key, label, value)]
BLOCKS = {
    "about": [
        ("hero.lede", "Text: We expand STEM access for underserved students in Uganda thr", "We expand STEM access for underserved students in Uganda through scholarships, mentorship, and hands-on learning."),
        ("origin.heading", "Text: Why we began", "Why we began"),
        ("origin.para1", "Text: For many students, the barrier is not ability. It is the cos", "For many students, the barrier is not ability. It is the cost of education, limited exposure to STEM careers, lack of mentorship, and the absence of professional networks that can help them imagine and prepare for a different future."),
        ("origin.para2", "Text: The foundation was created to help close that gap. Our work ", "The foundation was created to help close that gap. Our work focuses on supporting students not only with financial assistance, but also with guidance, encouragement, and real world exposure that helps them build confidence and direction."),
        ("origin.para3", "Text: We believe that when students are given access to opportunit", "We believe that when students are given access to opportunity, they can become engineers, scientists, researchers, entrepreneurs, educators, and problem solvers who strengthen their communities and contribute to global progress."),
        ("mission.eyebrow", "Text: What drives us", "What drives us"),
        ("mission.heading", "Text: Mission & Vision", "Mission & Vision"),
        ("mission.mission", "Text: To empower underserved students through access to STEM educa", "To empower underserved students through access to STEM education, scholarships, mentorship, and innovation driven opportunities that prepare them to become future leaders and problem solvers."),
        ("mission.vision", "Text: A world where every student, regardless of background, has t", "A world where every student, regardless of background, has the opportunity to access quality STEM education and contribute to solving local and global challenges."),
        ("founder.eyebrow", "Text: Founder’s Journey", "Founder’s Journey"),
        ("founder.heading", "Text: A foundation shaped by education, engineering, and service", "A foundation shaped by education, engineering, and service"),
        ("founder.para1", "Text: Jdiobe STEM Foundation was founded by Dr. Muwanika Jdiobe, a", "Jdiobe STEM Foundation was founded by Dr. Muwanika Jdiobe, an aerospace engineer, educator, and researcher committed to expanding access to STEM education globally."),
        ("founder.para2", "Text: His background in engineering and academia shaped the founda", "His background in engineering and academia shaped the foundation’s belief that education should connect knowledge with real world opportunity. Through his own academic and professional journey, Dr. Jdiobe recognized how mentorship, exposure, and support can change what a student believes is possible."),
        ("founder.para3", "Text: The foundation reflects that conviction. It is designed to h", "The foundation reflects that conviction. It is designed to help students access education, develop confidence, connect with mentors, and pursue STEM pathways that can transform their futures."),
        ("founder.para4", "Text: Dr. Jdiobe’s journey from the classrooms of Uganda to earnin", "Dr. Jdiobe’s journey from the classrooms of Uganda to earning a Ph.D. in Mechanical and Aerospace Engineering in the United States inspired a vision to give back. What began as personal outreach grew into a cross-border nonprofit bridging continents, resources, and ideas for the next generation of STEM leaders."),
        ("values.heading", "Text: The principles that guide our work", "The principles that guide our work"),
        ("values.access", "Text: We believe capable students should not be limited by financi", "We believe capable students should not be limited by financial barriers, geography, or lack of exposure."),
        ("values.mentorship", "Text: We believe guidance from educators, professionals, and role ", "We believe guidance from educators, professionals, and role models can change the direction of a student’s life."),
        ("values.innovation", "Text: We encourage students to use STEM knowledge to solve real pr", "We encourage students to use STEM knowledge to solve real problems in their communities and beyond."),
        ("values.sustainability", "Text: We are committed to building opportunities that create lasti", "We are committed to building opportunities that create lasting impact for students, families, and communities."),
        ("where.eyebrow", "Text: Where We Work", "Where We Work"),
        ("where.heading", "Text: Rooted in Uganda, connected to global opportunity", "Rooted in Uganda, connected to global opportunity"),
        ("where.para", "Text: Our goal is to connect local talent with the resources, ment", "Our goal is to connect local talent with the resources, mentorship, and learning experiences needed to participate in a global STEM future. Our work continues to grow through partnerships with schools, universities, and communities united by the belief that brilliance exists everywhere, but opportunity must be built."),
        ("forward.eyebrow", "Text: Moving Forward", "Moving Forward"),
        ("forward.heading", "Text: We are building pathways, not just programs.", "We are building pathways, not just programs."),
        ("forward.para", "Text: Our work is about helping students see what is possible, acc", "Our work is about helping students see what is possible, access the support they need, and become part of the next generation of STEM leaders."),
        ("cta.heading", "Text: Volunteer With Us", "Volunteer With Us"),
        ("cta.para", "Text: Join our mission to empower the next generation of STEM lead", "Join our mission to empower the next generation of STEM leaders. Whether you want to mentor, organize events, or support our outreach, your contribution makes a difference!"),
    ],
    "impact": [
        ("h1.measuring-progress-toward-a-future", "Heading: Measuring progress toward a future where more students can a", "Measuring progress toward a future where more students can access STEM opportunity."),
        ("p.our-impact-is-measured-not", "Paragraph: Our impact is measured not only by numbers, but by the stude", "Our impact is measured not only by numbers, but by the students who gain access, confidence, mentorship, and a clearer path toward STEM education and careers."),
        ("p.impact-snapshot", "Paragraph: Impact Snapshot", "Impact Snapshot"),
        ("h2.early-progress-real-students-and", "Heading: Early progress, real students, and growing momentum", "Early progress, real students, and growing momentum"),
        ("p.these-figures-should-be-updated", "Paragraph: These figures should be updated regularly as programs expand", "These figures should be updated regularly as programs expand. Even at an early stage, clear reporting helps donors, partners, and grant reviewers understand what has already begun."),
        ("h3.students-supported", "Sub-heading: Students Supported", "Students Supported"),
        ("p.students-reached-through-scholarships-guidance", "Paragraph: Students reached through scholarships, guidance, mentorship,", "Students reached through scholarships, guidance, mentorship, or STEM focused support."),
        ("h3.scholarships-awarded", "Sub-heading: Scholarships Awarded", "Scholarships Awarded"),
        ("p.scholarship-support-provided-to-students", "Paragraph: Scholarship support provided to students pursuing education ", "Scholarship support provided to students pursuing education in STEM related fields."),
        ("h3.active-initiatives", "Sub-heading: Active Initiatives", "Active Initiatives"),
        ("p.ongoing-efforts-focused-on-scholarships", "Paragraph: Ongoing efforts focused on scholarships, mentorship, and stu", "Ongoing efforts focused on scholarships, mentorship, and student opportunity building."),
        ("h3.primary-area-of-operation", "Sub-heading: Primary Area of Operation", "Primary Area of Operation"),
        ("p.current-work-is-focused-on", "Paragraph: Current work is focused on expanding access for underserved ", "Current work is focused on expanding access for underserved students in Uganda."),
        ("p.impact-story", "Paragraph: Impact Story", "Impact Story"),
        ("h2.behind-every-number-is-a", "Heading: Behind every number is a student with potential.", "Behind every number is a student with potential."),
        ("p.one-of-the-foundations-early", "Paragraph: One of the foundation’s early priorities has been helping st", "One of the foundation’s early priorities has been helping students pursue STEM pathways that may otherwise feel out of reach because of financial barriers, limited exposure, or lack of guidance."),
        ("p.through-scholarship-support-and-mentorship", "Paragraph: Through scholarship support and mentorship, students receive", "Through scholarship support and mentorship, students receive more than financial assistance. They receive encouragement, direction, and a reminder that their goals are possible."),
        ("p.for-students-pursuing-fields-such", "Paragraph: For students pursuing fields such as engineering, science, a", "For students pursuing fields such as engineering, science, and technology, this support can make the difference between pausing a dream and continuing toward a career with long term impact."),
        ("p.what-we-measure", "Paragraph: What We Measure", "What We Measure"),
        ("h2.we-track-outcomes-that-show", "Heading: We track outcomes that show whether students are moving forw", "We track outcomes that show whether students are moving forward."),
        ("p.our-work-is-strongest-when", "Paragraph: Our work is strongest when it can be measured. As programs g", "Our work is strongest when it can be measured. As programs grow, we will continue tracking both quantitative and qualitative indicators of student progress."),
        ("h3.access-to-education", "Sub-heading: Access to Education", "Access to Education"),
        ("p.students-receive-support-that-helps", "Paragraph: Students receive support that helps reduce financial barrier", "Students receive support that helps reduce financial barriers and makes STEM education more reachable."),
        ("h3.increased-confidence", "Sub-heading: Increased Confidence", "Increased Confidence"),
        ("p.mentorship-and-exposure-help-students", "Paragraph: Mentorship and exposure help students see themselves as futu", "Mentorship and exposure help students see themselves as future engineers, scientists, researchers, and innovators."),
        ("h3.career-direction", "Sub-heading: Career Direction", "Career Direction"),
        ("p.guidance-helps-students-understand-academic", "Paragraph: Guidance helps students understand academic pathways, profes", "Guidance helps students understand academic pathways, professional options, and the steps needed to pursue STEM careers."),
        ("h3.innovation-mindset", "Sub-heading: Innovation Mindset", "Innovation Mindset"),
        ("p.students-are-encouraged-to-think", "Paragraph: Students are encouraged to think beyond the classroom and ap", "Students are encouraged to think beyond the classroom and apply STEM knowledge to real community challenges."),
        ("p.evidence-of-activity", "Paragraph: Evidence of Activity", "Evidence of Activity"),
        ("h2.impact-grows-through-consistent-visible", "Heading: Impact grows through consistent, visible action.", "Impact grows through consistent, visible action."),
        ("p.from-scholarships-and-mentorship-to", "Paragraph: From scholarships and mentorship to hands-on STEM learning, ", "From scholarships and mentorship to hands-on STEM learning, our programs create progress students and partners can see and measure."),
        ("p.each-area-below-reflects-work", "Paragraph: Each area below reflects work already underway — not future ", "Each area below reflects work already underway — not future plans — as we build toward broader reach across Uganda."),
        ("h3.scholarship-support", "Sub-heading: Scholarship support", "Scholarship support"),
        ("p.financial-assistance-for-stem-focused", "Paragraph: Financial assistance for STEM-focused students covering tuit", "Financial assistance for STEM-focused students covering tuition, materials, and related costs so education stays within reach."),
        ("h3.mentorship-guidance", "Sub-heading: Mentorship & guidance", "Mentorship & guidance"),
        ("p.one-on-one-and-group", "Paragraph: One-on-one and group mentorship connecting underserved learn", "One-on-one and group mentorship connecting underserved learners with educators and professionals who help shape their academic path."),
        ("h3.engineering-science-pathways", "Sub-heading: Engineering & science pathways", "Engineering & science pathways"),
        ("p.targeted-support-for-students-pursuing", "Paragraph: Targeted support for students pursuing engineering, science,", "Targeted support for students pursuing engineering, science, and technology — from coursework guidance to exposure to real-world STEM work."),
        ("h3.partnerships-outreach", "Sub-heading: Partnerships & outreach", "Partnerships & outreach"),
        ("p.early-stage-collaborations-with-schools", "Paragraph: Early-stage collaborations with schools, communities, and or", "Early-stage collaborations with schools, communities, and organizations across Uganda to expand access and bring STEM opportunity to more students."),
        ("p.looking-ahead", "Paragraph: Looking Ahead", "Looking Ahead"),
        ("h2.our-next-phase-is-focused", "Heading: Our next phase is focused on scale, structure, and stronger ", "Our next phase is focused on scale, structure, and stronger measurement."),
        ("p.as-the-foundation-grows-we", "Paragraph: As the foundation grows, we aim to expand the number of stud", "As the foundation grows, we aim to expand the number of students reached while strengthening the systems used to track outcomes, report progress, and sustain long term impact."),
        ("p.expand-scholarship-support-for-more", "Paragraph: Expand scholarship support for more STEM students", "Expand scholarship support for more STEM students"),
        ("p.develop-structured-mentorship-cohorts", "Paragraph: Develop structured mentorship cohorts", "Develop structured mentorship cohorts"),
        ("p.launch-more-hands-on-stem", "Paragraph: Launch more hands on STEM learning activities", "Launch more hands on STEM learning activities"),
        ("p.build-stronger-partnerships-with-schools", "Paragraph: Build stronger partnerships with schools, universities, and ", "Build stronger partnerships with schools, universities, and community organizations"),
        ("p.support-the-impact", "Paragraph: Support the Impact", "Support the Impact"),
        ("h2.help-more-students-move-from", "Heading: Help more students move from potential to opportunity.", "Help more students move from potential to opportunity."),
        ("p.your-support-helps-expand-scholarships", "Paragraph: Your support helps expand scholarships, mentorship, STEM tra", "Your support helps expand scholarships, mentorship, STEM training, and innovation opportunities for underserved students in Uganda."),
    ],
    "uganda": [
        ("p.uganda-is-where-the-jdiobe", "Paragraph: Uganda is where the Jdiobe STEM Foundation began. We work di", "Uganda is where the Jdiobe STEM Foundation began. We work directly with schools, teachers, and communities to remove the practical barriers that keep capable students out of science and engineering."),
        ("p.on-the-ground", "Paragraph: On the ground", "On the ground"),
        ("h2.what-our-work-in-uganda", "Heading: What our work in Uganda looks like", "What our work in Uganda looks like"),
        ("p.scholarships", "Paragraph: Scholarships", "Scholarships"),
        ("p.tuition-materials-and-travel-support", "Paragraph: Tuition, materials, and travel support so cost is never the ", "Tuition, materials, and travel support so cost is never the reason a student stops."),
        ("p.classroom-lab", "Paragraph: Classroom & lab", "Classroom & lab"),
        ("p.practical-workshops-that-connect-the", "Paragraph: Practical workshops that connect the syllabus to real tools ", "Practical workshops that connect the syllabus to real tools and real problems."),
        ("p.local-educators-and-stem-professionals", "Paragraph: Local educators and STEM professionals walking with each coh", "Local educators and STEM professionals walking with each cohort through the year."),
        ("p.student-led-builds-in-robotics", "Paragraph: Student-led builds in robotics, assistive technology, and su", "Student-led builds in robotics, assistive technology, and sustainable design."),
        ("h2.hands-on-stem-education", "Heading: Hands-on STEM education", "Hands-on STEM education"),
        ("p.workshops-and-school-partnerships-that", "Paragraph: Workshops and school partnerships that put equipment in stud", "Workshops and school partnerships that put equipment in students' hands. Learners move from theory to circuits, sensors, and structures they build and test themselves."),
        ("h2.student-led-innovation", "Heading: Student-led innovation", "Student-led innovation"),
        ("p.teams-identify-a-problem-in", "Paragraph: Teams identify a problem in their own community and build to", "Teams identify a problem in their own community and build toward it — assistive devices, robotics, translation tools, environmental monitoring. The brief is always local."),
        ("p.looking-ahead", "Paragraph: Looking ahead", "Looking ahead"),
        ("h2.where-we-are-focusing-next", "Heading: Where we are focusing next in Uganda", "Where we are focusing next in Uganda"),
        ("p.deepening-what-already-works-and", "Paragraph: Deepening what already works, and extending it to more schoo", "Deepening what already works, and extending it to more schools and districts."),
        ("h2.support-a-student-in-uganda", "Heading: Support a student in Uganda", "Support a student in Uganda"),
        ("p.your-support-goes-directly-into", "Paragraph: Your support goes directly into scholarships, equipment, and", "Your support goes directly into scholarships, equipment, and mentorship for students who already have the ambition."),
    ],
    "south-sudan": [
        ("p.extending-the-foundation-s-work", "Paragraph: Extending the foundation's work beyond Uganda. In South Suda", "Extending the foundation's work beyond Uganda. In South Sudan we focus on the earliest barriers to STEM — access to teaching, equipment, and a reason to believe a technical career is possible."),
        ("p.our-approach", "Paragraph: Our approach", "Our approach"),
        ("h2.building-the-foundations-first", "Heading: Building the foundations first", "Building the foundations first"),
        ("p.we-start-where-the-need", "Paragraph: We start where the need is most basic and build upward — wor", "We start where the need is most basic and build upward — working with local schools and partners rather than around them."),
        ("p.getting-learning-materials-and-basic", "Paragraph: Getting learning materials and basic equipment into classroo", "Getting learning materials and basic equipment into classrooms that have neither."),
        ("p.supporting-teachers-with-practical-stem", "Paragraph: Supporting teachers with practical STEM training they can ap", "Supporting teachers with practical STEM training they can apply immediately."),
        ("p.connecting-students-to-people-who", "Paragraph: Connecting students to people who have walked the path they ", "Connecting students to people who have walked the path they are considering."),
        ("p.opening-routes-to-further-study", "Paragraph: Opening routes to further study, regionally and internationa", "Opening routes to further study, regionally and internationally."),
        ("h2.teacher-support-and-training", "Heading: Teacher support and training", "Teacher support and training"),
        ("p.the-fastest-way-to-reach", "Paragraph: The fastest way to reach many students is through the person", "The fastest way to reach many students is through the person already standing in front of them. We work with teachers on practical STEM instruction, low-cost demonstrations, and shared materials."),
        ("h2.access-to-equipment-and-materials", "Heading: Access to equipment and materials", "Access to equipment and materials"),
        ("p.practical-science-needs-practical-things", "Paragraph: Practical science needs practical things. We supply kits and", "Practical science needs practical things. We supply kits and materials that let a classroom run real experiments, chosen for durability and for what can be repaired or replaced locally."),
        ("p.looking-ahead", "Paragraph: Looking ahead", "Looking ahead"),
        ("h2.growing-this-work-responsibly", "Heading: Growing this work responsibly", "Growing this work responsibly"),
        ("p.we-would-rather-do-a", "Paragraph: We would rather do a small amount well and grow from proof t", "We would rather do a small amount well and grow from proof than announce more than we can sustain."),
        ("h2.help-us-reach-further", "Heading: Help us reach further", "Help us reach further"),
        ("p.whether-as-a-donor-a", "Paragraph: Whether as a donor, a school, or a partner organisation — ge", "Whether as a donor, a school, or a partner organisation — get in touch about the work in South Sudan."),
    ],
    "youth-stem": [
        ("p.youth-stem-school-program", "Paragraph: Youth STEM School Program", "Youth STEM School Program"),
        ("h1.inspiring-young-minds-building-future", "Heading: Inspiring young minds, building future innovators", "Inspiring young minds, building future innovators"),
        ("p.hands-on-stem-experiences-that", "Paragraph: Hands-on STEM experiences that introduce primary and middle ", "Hands-on STEM experiences that introduce primary and middle school students to science, technology, engineering, and mathematics through fun, engaging, and interactive learning."),
        ("h2.every-child-is-born-curious", "Heading: Every child is born curious", "Every child is born curious"),
        ("p.early-exposure-to-stem-helps", "Paragraph: Early exposure to STEM helps students develop confidence, cr", "Early exposure to STEM helps students develop confidence, creativity, teamwork, and problem-solving skills that prepare them for success in school and future careers."),
        ("p.our-interactive-workshops-transform-classrooms", "Paragraph: Our interactive workshops transform classrooms into innovati", "Our interactive workshops transform classrooms into innovation labs where students learn by exploring, building, experimenting, and discovering — while introducing them to careers they may never have imagined."),
        ("h2.learning-that-sticks", "Heading: Learning that sticks", "Learning that sticks"),
        ("h3.hands-on-learning", "Sub-heading: Hands-On Learning", "Hands-On Learning"),
        ("p.students-take-part-in-exciting", "Paragraph: Students take part in exciting experiments and engineering c", "Students take part in exciting experiments and engineering challenges that make STEM fun and engaging."),
        ("h3.stem-mentors", "Sub-heading: STEM Mentors", "STEM Mentors"),
        ("p.volunteers-engineers-scientists-and-university", "Paragraph: Volunteers, engineers, scientists, and university students i", "Volunteers, engineers, scientists, and university students inspire young learners through mentorship and interactive activities."),
        ("h3.future-ready-skills", "Sub-heading: Future-Ready Skills", "Future-Ready Skills"),
        ("p.students-build-creativity-communication-teamwork", "Paragraph: Students build creativity, communication, teamwork, leadersh", "Students build creativity, communication, teamwork, leadership, and critical thinking that extend beyond the classroom."),
        ("h2.what-students-experience", "Heading: What students experience", "What students experience"),
        ("h3.science-experiments", "Sub-heading: Science Experiments", "Science Experiments"),
        ("p.interactive-experiments-that-make-science", "Paragraph: Interactive experiments that make science exciting.", "Interactive experiments that make science exciting."),
        ("p.build-and-program-simple-robots", "Paragraph: Build and program simple robots.", "Build and program simple robots."),
        ("p.learn-programming-through-games-and", "Paragraph: Learn programming through games and challenges.", "Learn programming through games and challenges."),
        ("h3.drone-demonstrations", "Sub-heading: Drone Demonstrations", "Drone Demonstrations"),
        ("p.experience-the-future-of-aviation", "Paragraph: Experience the future of aviation and technology.", "Experience the future of aviation and technology."),
        ("h3.engineering-challenges", "Sub-heading: Engineering Challenges", "Engineering Challenges"),
        ("p.design-build-test-and-improve", "Paragraph: Design, build, test, and improve creative solutions.", "Design, build, test, and improve creative solutions."),
        ("p.collaborative-competitions-that-strengthen-teamwork", "Paragraph: Collaborative competitions that strengthen teamwork and prob", "Collaborative competitions that strengthen teamwork and problem solving."),
        ("h2.four-pillars-of-discovery", "Heading: Four pillars of discovery", "Four pillars of discovery"),
        ("h2.a-day-with-jdiobe-stem", "Heading: A day with Jdiobe STEM", "A day with Jdiobe STEM"),
        ("h3.welcome-icebreaker", "Sub-heading: Welcome & Icebreaker", "Welcome & Icebreaker"),
        ("h3.interactive-presentation", "Sub-heading: Interactive Presentation", "Interactive Presentation"),
        ("h3.hands-on-workshops", "Sub-heading: Hands-On Workshops", "Hands-On Workshops"),
        ("h3.engineering-challenge", "Sub-heading: Engineering Challenge", "Engineering Challenge"),
        ("h3.team-competition", "Sub-heading: Team Competition", "Team Competition"),
        ("h3.awards-certificates", "Sub-heading: Awards & Certificates", "Awards & Certificates"),
        ("h2.skills-for-life", "Heading: Skills for life", "Skills for life"),
        ("h2.what-can-you-become", "Heading: What can you become?", "What can you become?"),
        ("p.helping-children-connect-today-s", "Paragraph: Helping children connect today's activities with tomorrow's ", "Helping children connect today's activities with tomorrow's careers."),
        ("h2.see-stem-in-action", "Heading: See STEM in action", "See STEM in action"),
        ("h2.creating-opportunities-through-stem", "Heading: Creating opportunities through STEM", "Creating opportunities through STEM"),
        ("h2.in-their-words", "Heading: In their words", "In their words"),
        ("h2.this-is-just-the-beginning", "Heading: This is just the beginning", "This is just the beginning"),
        ("p.we-support-students-from-their", "Paragraph: We support students from their first exposure to STEM all th", "We support students from their first exposure to STEM all the way to university and professional careers."),
        ("p.youth-stem-school", "Paragraph: Youth STEM School", "Youth STEM School"),
        ("p.secondary-research", "Paragraph: Secondary Research", "Secondary Research"),
        ("p.scholarships", "Paragraph: Scholarships", "Scholarships"),
        ("p.university-research", "Paragraph: University Research", "University Research"),
        ("p.internships-mentorship", "Paragraph: Internships & Mentorship", "Internships & Mentorship"),
        ("p.careers-leadership", "Paragraph: Careers & Leadership", "Careers & Leadership"),
        ("h2.ready-to-inspire-the-next", "Heading: Ready to inspire the next generation?", "Ready to inspire the next generation?"),
        ("p.the-jdiobe-stem-foundation-partners", "Paragraph: The Jdiobe STEM Foundation partners with schools to deliver ", "The Jdiobe STEM Foundation partners with schools to deliver exciting STEM experiences that spark curiosity and prepare students for the future."),
    ],
    "scholarship": [
        ("p.stem-scholarship-program", "Paragraph: STEM Scholarship Program", "STEM Scholarship Program"),
        ("h1.supporting-future-stem-leaders", "Heading: Supporting future STEM leaders", "Supporting future STEM leaders"),
        ("p.scholarships-that-reduce-financial-barriers", "Paragraph: Scholarships that reduce financial barriers while providing ", "Scholarships that reduce financial barriers while providing mentorship, leadership development, and professional growth for outstanding students pursuing STEM education."),
        ("h2.opening-doors-for-the-next", "Heading: Opening doors for the next generation", "Opening doors for the next generation"),
        ("h3.dr-ron-and-cara-beer", "Sub-heading: Dr. Ron and Cara Beer STEM Scholarship", "Dr. Ron and Cara Beer STEM Scholarship"),
        ("p.established-by-dr-ron-and", "Paragraph: Established by Dr. Ron and Cara Beer for STEM Students.", "Established by Dr. Ron and Cara Beer for STEM Students."),
        ("p.established-through-the-generosity-of", "Paragraph: Established through the generosity of Dr. Ron and Cara Beer,", "Established through the generosity of Dr. Ron and Cara Beer, this scholarship helps remove financial barriers for students pursuing STEM education."),
        ("h3.regina-henry-scholarship", "Sub-heading: Regina Henry Scholarship", "Regina Henry Scholarship"),
        ("p.established-by-regina-henry", "Paragraph: Established by Regina Henry", "Established by Regina Henry"),
        ("p.supporting-promising-students-whose-determination", "Paragraph: Supporting promising students whose determination, character", "Supporting promising students whose determination, character, and commitment to education position them to become future leaders in STEM and their communities."),
        ("p.it-helps-students-continue-their", "Paragraph: It helps students continue their education with confidence b", "It helps students continue their education with confidence by providing financial support, encouragement, and a stronger path toward STEM leadership."),
        ("p.this-scholarship-includes", "Paragraph: This scholarship includes", "This scholarship includes"),
        ("h3.jdiobe-stem-scholarship", "Sub-heading: Jdiobe STEM Scholarship", "Jdiobe STEM Scholarship"),
        ("p.our-foundation-s-flagship-scholarship", "Paragraph: Our foundation's flagship scholarship", "Our foundation's flagship scholarship"),
        ("p.awarded-directly-by-jdiobe-stem", "Paragraph: Awarded directly by Jdiobe STEM Foundation to high-potential", "Awarded directly by Jdiobe STEM Foundation to high-potential students, removing practical barriers so they can begin or continue their STEM education journey."),
        ("p.this-scholarship-includes-2", "Paragraph: This scholarship includes", "This scholarship includes"),
        ("h2.support-that-goes-beyond-the", "Heading: Support that goes beyond the classroom", "Support that goes beyond the classroom"),
        ("h3.tuition-assistance", "Sub-heading: Tuition Assistance", "Tuition Assistance"),
        ("p.reducing-the-financial-barriers-to", "Paragraph: Reducing the financial barriers to STEM education.", "Reducing the financial barriers to STEM education."),
        ("p.guidance-from-engineers-scientists-and", "Paragraph: Guidance from engineers, scientists, and educators.", "Guidance from engineers, scientists, and educators."),
        ("h3.leadership-development", "Sub-heading: Leadership Development", "Leadership Development"),
        ("p.building-the-skills-to-lead", "Paragraph: Building the skills to lead in STEM and community.", "Building the skills to lead in STEM and community."),
        ("h3.professional-growth", "Sub-heading: Professional Growth", "Professional Growth"),
        ("p.pathways-into-research-internships-and", "Paragraph: Pathways into research, internships, and careers.", "Pathways into research, internships, and careers."),
        ("h2.fund-the-future-of-stem", "Heading: Fund the future of STEM", "Fund the future of STEM"),
        ("p.your-generosity-can-help-remove", "Paragraph: Your generosity can help remove financial barriers for a tal", "Your generosity can help remove financial barriers for a talented student — or establish a named scholarship of your own. Together we can turn potential into opportunity."),
    ],
    "aerospace-institute": [
        ("h1.welcome-to-the-institute", "Heading: Welcome to the institute", "Welcome to the institute"),
        ("p.the-aerospace-institute-is-the", "Paragraph: The Aerospace Institute is the foundation's next major build", "The Aerospace Institute is the foundation's next major build: a dedicated home for aerospace education, research, and industry partnership. It has not opened yet. Programme design and partner agreements are the work in front of us now, and the doors will open once the facility and the curriculum are both ready."),
        ("p.when-it-does-open-the", "Paragraph: When it does open, the institute will run focused pathways f", "When it does open, the institute will run focused pathways for students who want to work in aviation and space technology — rigorous fundamentals, hands-on build-and-test cycles, and the professional habits that transfer to university and the workforce."),
        ("p.we-are-publishing-the-plan", "Paragraph: We are publishing the plan early on purpose. The schools, un", "We are publishing the plan early on purpose. The schools, universities, and industry partners who join now are the ones who will shape what gets built."),
        ("h2.what-students-will-study", "Heading: What students will study", "What students will study"),
        ("p.four-strands-taught-together-rather", "Paragraph: Four strands, taught together rather than in sequence — a st", "Four strands, taught together rather than in sequence — a student should be flying, measuring, and arguing about a design in the same term."),
        ("h3.flight-science", "Sub-heading: Flight science", "Flight science"),
        ("p.aerodynamics-propulsion-stability-and-mission", "Paragraph: Aerodynamics, propulsion, stability, and mission design — th", "Aerodynamics, propulsion, stability, and mission design — the physics a vehicle has to obey before anyone builds one."),
        ("h3.safety-systems", "Sub-heading: Safety & systems", "Safety & systems"),
        ("p.systems-thinking-testing-discipline-and", "Paragraph: Systems thinking, testing discipline, and operations awarene", "Systems thinking, testing discipline, and operations awareness. How aircraft are certified, maintained, and flown without incident."),
        ("h3.design-fabrication", "Sub-heading: Design & fabrication", "Design & fabrication"),
        ("p.drawing-machining-and-assembling-real", "Paragraph: Drawing, machining, and assembling real parts — materials an", "Drawing, machining, and assembling real parts — materials and structures learned at the bench rather than only on the page."),
        ("h3.data-control", "Sub-heading: Data & control", "Data & control"),
        ("p.instrumentation-avionics-and-flight-data", "Paragraph: Instrumentation, avionics, and flight data. Reading what a t", "Instrumentation, avionics, and flight data. Reading what a test actually told you and changing the design because of it."),
        ("p.planned-facilities", "Paragraph: Planned facilities", "Planned facilities"),
        ("h2.what-we-intend-to-build", "Heading: What we intend to build", "What we intend to build"),
        ("p.three-things-the-region-does", "Paragraph: Three things the region does not currently have in one place", "Three things the region does not currently have in one place, and the reason the institute is worth building at all."),
        ("h3.engineering-studios", "Sub-heading: Engineering studios", "Engineering studios"),
        ("p.design-fabrication-and-integration-space", "Paragraph: Design, fabrication, and integration space where a cohort ca", "Design, fabrication, and integration space where a cohort can take a vehicle from sketch to flight test without leaving the building."),
        ("h3.research-lab", "Sub-heading: Research lab", "Research lab"),
        ("p.mentored-r-d-unmanned-systems", "Paragraph: Mentored R&D — unmanned systems, materials, and instrumentat", "Mentored R&D — unmanned systems, materials, and instrumentation — carried from a question through validation to a paper students can defend."),
        ("h3.partner-network", "Sub-heading: Partner network", "Partner network"),
        ("p.standing-links-to-universities-aviation", "Paragraph: Standing links to universities, aviation firms, and alumni s", "Standing links to universities, aviation firms, and alumni so internships, guest teaching, and equipment are part of the institute, not favours."),
        ("p.the-road-there", "Paragraph: The road there", "The road there"),
        ("h2.how-the-institute-gets-built", "Heading: How the institute gets built", "How the institute gets built"),
        ("p.four-stages-in-order-we", "Paragraph: Four stages, in order. We will publish an opening date here ", "Four stages, in order. We will publish an opening date here once the site and the funding for it are both secured — not before."),
        ("h3.curriculum-and-partnerships", "Sub-heading: Curriculum and partnerships", "Curriculum and partnerships"),
        ("p.designing-the-pathways-with-practising", "Paragraph: Designing the pathways with practising engineers, and signin", "Designing the pathways with practising engineers, and signing the university and industry partners who will teach, examine, and hire from them."),
        ("h3.site-and-funding", "Sub-heading: Site and funding", "Site and funding"),
        ("p.securing-the-land-the-workshop", "Paragraph: Securing the land, the workshop and lab build, and the capit", "Securing the land, the workshop and lab build, and the capital behind it. This is the stage donors and sponsors move fastest."),
        ("h3.pilot-cohort", "Sub-heading: Pilot cohort", "Pilot cohort"),
        ("p.a-small-first-intake-run", "Paragraph: A small first intake run out of partner facilities, so the t", "A small first intake run out of partner facilities, so the teaching is tested on real students before the full institute opens."),
        ("h3.the-institute-opens", "Sub-heading: The institute opens", "The institute opens"),
        ("p.full-intake-the-research-programme", "Paragraph: Full intake, the research programme running, and placements ", "Full intake, the research programme running, and placements with the partners built up in stage one."),
        ("h2.help-us-build-it", "Heading: Help us build it", "Help us build it"),
        ("p.the-institute-is-not-open", "Paragraph: The institute is not open, so there is nothing to apply to y", "The institute is not open, so there is nothing to apply to yet — but there is plenty to join. Schools and universities can shape the curriculum, firms can offer equipment, teaching, or placements, and donors can move the site forward."),
    ],
    "community-outreach": [
        ("p.community-stem-outreach", "Paragraph: Community STEM Outreach", "Community STEM Outreach"),
        ("h1.bringing-stem-education-beyond-the", "Heading: Bringing STEM education beyond the classroom", "Bringing STEM education beyond the classroom"),
        ("p.we-partner-with-schools-communities", "Paragraph: We partner with schools, communities, universities, and indu", "We partner with schools, communities, universities, and industry to deliver engaging STEM experiences that inspire curiosity, foster innovation, and expand educational opportunities for learners of all ages."),
        ("h2.making-stem-accessible-to-every", "Heading: Making STEM accessible to every community", "Making STEM accessible to every community"),
        ("p.every-student-deserves-the-opportunity", "Paragraph: Every student deserves the opportunity to discover science, ", "Every student deserves the opportunity to discover science, technology, engineering, and mathematics — regardless of where they live or their background. Through community outreach we bring STEM directly to schools, community centers, libraries, and public events, creating experiences that inspire lifelong learning and future careers."),
        ("h3.stem-workshops", "Sub-heading: STEM Workshops", "STEM Workshops"),
        ("p.interactive-science-and-engineering-activities", "Paragraph: Interactive science and engineering activities designed to s", "Interactive science and engineering activities designed to spark curiosity."),
        ("h3.robotics-demonstrations", "Sub-heading: Robotics Demonstrations", "Robotics Demonstrations"),
        ("p.students-explore-robotics-through-live", "Paragraph: Students explore robotics through live demonstrations and be", "Students explore robotics through live demonstrations and beginner programming."),
        ("h3.drone-aviation-experiences", "Sub-heading: Drone & Aviation Experiences", "Drone & Aviation Experiences"),
        ("p.hands-on-exposure-to-drones", "Paragraph: Hands-on exposure to drones, aerospace engineering, and avia", "Hands-on exposure to drones, aerospace engineering, and aviation careers."),
        ("h3.science-discovery-days", "Sub-heading: Science Discovery Days", "Science Discovery Days"),
        ("p.exciting-experiments-that-make-science", "Paragraph: Exciting experiments that make science fun and memorable.", "Exciting experiments that make science fun and memorable."),
        ("h3.technology-coding-sessions", "Sub-heading: Technology & Coding Sessions", "Technology & Coding Sessions"),
        ("p.students-learn-digital-skills-coding", "Paragraph: Students learn digital skills, coding, and emerging technolo", "Students learn digital skills, coding, and emerging technologies."),
        ("h3.stem-career-talks", "Sub-heading: STEM Career Talks", "STEM Career Talks"),
        ("p.professionals-share-their-educational-journeys", "Paragraph: Professionals share their educational journeys, career exper", "Professionals share their educational journeys, career experiences, and advice."),
        ("h2.we-bring-stem-to", "Heading: We bring STEM to", "We bring STEM to"),
        ("h2.how-a-day-unfolds", "Heading: How a day unfolds", "How a day unfolds"),
        ("h3.welcome-introduction", "Sub-heading: Welcome & Introduction", "Welcome & Introduction"),
        ("h3.interactive-presentation", "Sub-heading: Interactive Presentation", "Interactive Presentation"),
        ("h3.hands-on-activity-stations", "Sub-heading: Hands-On Activity Stations", "Hands-On Activity Stations"),
        ("h3.engineering-challenge", "Sub-heading: Engineering Challenge", "Engineering Challenge"),
        ("h3.career-exploration", "Sub-heading: Career Exploration", "Career Exploration"),
        ("h3.questions-discussion", "Sub-heading: Questions & Discussion", "Questions & Discussion"),
        ("h3.certificates-group-photo", "Sub-heading: Certificates & Group Photo", "Certificates & Group Photo"),
        ("h2.hands-on-from-start-to", "Heading: Hands-on from start to finish", "Hands-on from start to finish"),
        ("h2.stem-in-the-community", "Heading: STEM in the community", "STEM in the community"),
        ("h3.stem-festival-exhibitions", "Sub-heading: STEM Festival Exhibitions", "STEM Festival Exhibitions"),
        ("p.interactive-booths-featuring-robotics-engineering", "Paragraph: Interactive booths featuring robotics, engineering, and tech", "Interactive booths featuring robotics, engineering, and technology demonstrations."),
        ("h3.science-in-the-community", "Sub-heading: Science in the Community", "Science in the Community"),
        ("p.hands-on-experiments-designed-to", "Paragraph: Hands-on experiments designed to inspire curiosity and scien", "Hands-on experiments designed to inspire curiosity and scientific thinking."),
        ("h3.engineering-challenge-days", "Sub-heading: Engineering Challenge Days", "Engineering Challenge Days"),
        ("p.students-collaborate-in-teams-to", "Paragraph: Students collaborate in teams to design, build, and test eng", "Students collaborate in teams to design, build, and test engineering solutions."),
        ("h3.drone-discovery-workshops", "Sub-heading: Drone Discovery Workshops", "Drone Discovery Workshops"),
        ("p.learn-how-drones-are-transforming", "Paragraph: Learn how drones are transforming agriculture, healthcare, a", "Learn how drones are transforming agriculture, healthcare, and emergency response."),
        ("h2.why-community-stem-outreach-matters", "Heading: Why community STEM outreach matters", "Why community STEM outreach matters"),
        ("h3.inspire-curiosity", "Sub-heading: Inspire Curiosity", "Inspire Curiosity"),
        ("p.introduce-students-to-exciting-stem", "Paragraph: Introduce students to exciting STEM concepts through engagin", "Introduce students to exciting STEM concepts through engaging experiences."),
        ("h3.build-confidence", "Sub-heading: Build Confidence", "Build Confidence"),
        ("p.help-young-learners-develop-problem", "Paragraph: Help young learners develop problem-solving and critical thi", "Help young learners develop problem-solving and critical thinking skills."),
        ("h3.expand-opportunities", "Sub-heading: Expand Opportunities", "Expand Opportunities"),
        ("p.connect-students-with-mentors-educational", "Paragraph: Connect students with mentors, educational pathways, and fut", "Connect students with mentors, educational pathways, and future careers."),
        ("h3.strengthen-communities", "Sub-heading: Strengthen Communities", "Strengthen Communities"),
        ("p.create-partnerships-that-promote-lifelong", "Paragraph: Create partnerships that promote lifelong learning and innov", "Create partnerships that promote lifelong learning and innovation."),
        ("h2.building-stronger-stem-communities", "Heading: Building stronger STEM communities", "Building stronger STEM communities"),
        ("h2.moments-from-the-field", "Heading: Moments from the field", "Moments from the field"),
        ("h2.what-people-are-saying", "Heading: What people are saying", "What people are saying"),
        ("h2.let-s-expand-stem-together", "Heading: Let's expand STEM together", "Let's expand STEM together"),
        ("p.we-welcome-partnerships-with-schools", "Paragraph: We welcome partnerships with schools, universities, communit", "We welcome partnerships with schools, universities, community organizations, companies, government agencies, and volunteers who share our commitment to expanding STEM education."),
        ("h2.help-inspire-the-next-generation", "Heading: Help inspire the next generation", "Help inspire the next generation"),
        ("p.engineers-scientists-educators-university-students", "Paragraph: Engineers, scientists, educators, university students, and S", "Engineers, scientists, educators, university students, and STEM professionals can make a meaningful impact by sharing their knowledge and inspiring future innovators."),
        ("h2.part-of-one-connected-pathway", "Heading: Part of one connected pathway", "Part of one connected pathway"),
        ("p.youth-stem-school", "Paragraph: Youth STEM School", "Youth STEM School"),
        ("p.community-outreach", "Paragraph: Community Outreach", "Community Outreach"),
        ("p.secondary-research", "Paragraph: Secondary Research", "Secondary Research"),
        ("p.scholarships", "Paragraph: Scholarships", "Scholarships"),
        ("p.university-research", "Paragraph: University Research", "University Research"),
        ("p.careers-leadership", "Paragraph: Careers & Leadership", "Careers & Leadership"),
        ("h2.ready-to-bring-stem-to", "Heading: Ready to bring STEM to your community?", "Ready to bring STEM to your community?"),
        ("p.together-we-can-inspire-curiosity", "Paragraph: Together, we can inspire curiosity, create opportunities, an", "Together, we can inspire curiosity, create opportunities, and prepare the next generation of STEM leaders. We work with schools, community organizations, local governments, and corporate partners to deliver engaging STEM experiences tailored to your audience."),
    ],
    "secondary-research": [
        ("p.uganda-national-secondary-school-science", "Paragraph: Uganda National Secondary School Science Fair", "Uganda National Secondary School Science Fair"),
        ("h1.projects-research-and-the-science", "Heading: Projects, research, and the Science Fair", "Projects, research, and the Science Fair"),
        ("p.secondary-school-students-design-a", "Paragraph: Secondary school students design a real project, write a rea", "Secondary school students design a real project, write a real proposal, and defend it in front of judges — from a school fair, to a regional fair, to the national fair. No laboratory required."),
        ("h2.discover-research-before-university", "Heading: Discover research before university", "Discover research before university"),
        ("p.the-program-introduces-talented-secondary", "Paragraph: The program introduces talented secondary school students to", "The program introduces talented secondary school students to scientific research, engineering design, innovation, and entrepreneurship. Students work alongside university faculty, engineers, scientists, and industry professionals to develop practical solutions to real-world challenges while building the skills that prepare them for university and STEM careers."),
        ("h2.what-students-will-do", "Heading: What students will do", "What students will do"),
        ("p.how-it-works", "Paragraph: How it works", "How it works"),
        ("h2.from-an-idea-to-the", "Heading: From an idea to the national fair", "From an idea to the national fair"),
        ("p.projects-advance-from-a-school", "Paragraph: Projects advance from a school-level fair, to a regional fai", "Projects advance from a school-level fair, to a regional fair, to the national fair. Dates for each stage are announced to schools each year."),
        ("h2.six-categories-to-enter", "Heading: Six categories to enter", "Six categories to enter"),
        ("p.every-project-is-entered-in", "Paragraph: Every project is entered in one category. Choose the one you", "Every project is entered in one category. Choose the one your work sits in most naturally — judges compare projects within a category, not across them."),
        ("h2.imagine-what-you-could-build", "Heading: Imagine what you could build", "Imagine what you could build"),
        ("h3.autonomous-water-monitoring-robot", "Sub-heading: Autonomous Water Monitoring Robot", "Autonomous Water Monitoring Robot"),
        ("p.a-student-built-solution-for", "Paragraph: A student-built solution for testing water quality.", "A student-built solution for testing water quality."),
        ("h3.ai-crop-disease-detection", "Sub-heading: AI Crop Disease Detection", "AI Crop Disease Detection"),
        ("p.using-technology-to-support-farmers", "Paragraph: Using technology to support farmers.", "Using technology to support farmers."),
        ("h3.low-cost-solar-irrigation-system", "Sub-heading: Low-Cost Solar Irrigation System", "Low-Cost Solar Irrigation System"),
        ("p.a-low-cost-solution-for", "Paragraph: A low-cost solution for agriculture.", "A low-cost solution for agriculture."),
        ("h3.drone-based-medical-delivery", "Sub-heading: Drone-Based Medical Delivery", "Drone-Based Medical Delivery"),
        ("p.exploring-how-uavs-can-support", "Paragraph: Exploring how UAVs can support healthcare access.", "Exploring how UAVs can support healthcare access."),
        ("h3.smart-traffic-management", "Sub-heading: Smart Traffic Management", "Smart Traffic Management"),
        ("p.smarter-safer-roads-through-technology", "Paragraph: Smarter, safer roads through technology.", "Smarter, safer roads through technology."),
        ("h3.flood-prediction-using-ai", "Sub-heading: Flood Prediction Using AI", "Flood Prediction Using AI"),
        ("p.early-warning-to-protect-communities", "Paragraph: Early warning to protect communities.", "Early warning to protect communities."),
        ("h3.renewable-energy-solutions", "Sub-heading: Renewable Energy Solutions", "Renewable Energy Solutions"),
        ("p.clean-power-for-homes-and", "Paragraph: Clean power for homes and schools.", "Clean power for homes and schools."),
        ("h3.plastic-recycling-innovation", "Sub-heading: Plastic Recycling Innovation", "Plastic Recycling Innovation"),
        ("p.turning-waste-into-opportunity", "Paragraph: Turning waste into opportunity.", "Turning waste into opportunity."),
        ("h2.research-that-adds-up", "Heading: Research that adds up", "Research that adds up"),
        ("h2.where-students-will-work", "Heading: Where students will work", "Where students will work"),
        ("h2.present-compete-inspire", "Heading: Present. Compete. Inspire.", "Present. Compete. Inspire."),
        ("p.every-participating-student-presents-their", "Paragraph: Every participating student presents their research at the J", "Every participating student presents their research at the Jdiobe STEM Research Symposium before judges from universities and industry. Award categories may include:"),
        ("p.who-may-enter", "Paragraph: Who may enter", "Who may enter"),
        ("h2.any-student-any-school", "Heading: Any student, any school", "Any student, any school"),
        ("p.the-science-fair-is-open", "Paragraph: The Science Fair is open to students enrolled at a Ugandan s", "The Science Fair is open to students enrolled at a Ugandan secondary school, entering individually or as a team, supervised by a teacher mentor."),
        ("p.you-do-not-need-a", "Paragraph: You do not need a laboratory, and you do not need previous r", "You do not need a laboratory, and you do not need previous research experience. The strongest projects usually come from noticing something wrong close to home and being stubborn about measuring it."),
        ("p.exact-class-levels-any-age", "Paragraph: Exact class levels, any age limits and maximum team size are", "Exact class levels, any age limits and maximum team size are confirmed with schools each year when the handbook is released."),
        ("h3.what-it-costs", "Sub-heading: What it costs", "What it costs"),
        ("p.nothing-there-is-no-entry", "Paragraph: Nothing. There is no entry fee, and no money passes to your ", "Nothing. There is no entry fee, and no money passes to your school."),
        ("h3.can-my-project-be-funded", "Sub-heading: Can my project be funded?", "Can my project be funded?"),
        ("p.the-foundation-may-fund-part", "Paragraph: The Foundation may fund part of an approved project where th", "The Foundation may fund part of an approved project where there is demonstrated need, based on the itemised budget in your workbook. Funding is never guaranteed, and it is not required to take part — plenty of strong projects cost almost nothing."),
        ("p.the-proposal", "Paragraph: The proposal", "The proposal"),
        ("h2.what-you-are-asked-to", "Heading: What you are asked to write", "What you are asked to write"),
        ("p.the-proposal-workbook-walks-you", "Paragraph: The Proposal Workbook walks you through twenty-two sections.", "The Proposal Workbook walks you through twenty-two sections. It is long on purpose: most of it is teaching, and you fill in the blanks as you go."),
        ("h2.the-handbook-and-the-forms", "Heading: The handbook and the forms", "The handbook and the forms"),
        ("p.read-the-handbook-before-you", "Paragraph: Read the handbook before you start. Fill in the workbook as ", "Read the handbook before you start. Fill in the workbook as you go — it is designed to be worked through, not filled in at the end."),
        ("h2.register-your-project", "Heading: Register your project", "Register your project"),
        ("p.tell-us-who-you-are", "Paragraph: Tell us who you are and what you want to work on. This is th", "Tell us who you are and what you want to work on. This is the online step; the formal submission is the completed workbook, signed by you, your mentor and your head teacher, with the school stamp."),
        ("h2.answers-for-applicants", "Heading: Answers for applicants", "Answers for applicants"),
        ("h2.partner-with-us", "Heading: Partner with us", "Partner with us"),
        ("p.we-invite-universities-companies-researchers", "Paragraph: We invite universities, companies, researchers, engineers, s", "We invite universities, companies, researchers, engineers, sponsors, and schools to support student research and help build Africa's next generation of innovators."),
    ],
    "mentorship": [
        ("h1.nobody-gets-there-on-their", "Heading: Nobody gets there on their own.", "Nobody gets there on their own."),
        ("p.mentorship-pairs-students-with-the", "Paragraph: Mentorship pairs students with the educators and professiona", "Mentorship pairs students with the educators and professionals who have already walked the path they are trying to find — so the next decision is made with someone, not alone."),
        ("p.why-it-matters", "Paragraph: Why it matters", "Why it matters"),
        ("h2.the-gap-is-rarely-ability", "Heading: The gap is rarely ability.", "The gap is rarely ability."),
        ("p.a-student-in-uganda-or", "Paragraph: A student in Uganda or South Sudan can be the strongest math", "A student in Uganda or South Sudan can be the strongest mathematician in their class and still have no idea what an engineer does all day, which subjects a degree needs, or whether anyone like them has done it before. That is not a gap in talent. It is a gap in exposure and in networks — and it is the one a mentor closes."),
        ("p.mentorship-runs-alongside-the-other", "Paragraph: Mentorship runs alongside the other programmes rather than i", "Mentorship runs alongside the other programmes rather than instead of them. A scholarship pays the fees; a mentor is the person a student can ask what to do next."),
        ("h2.two-sides-of-the-same", "Heading: Two sides of the same pairing", "Two sides of the same pairing"),
        ("p.the-programme-is-written-down", "Paragraph: The programme is written down twice — once for the person gi", "The programme is written down twice — once for the person giving time, once for the student receiving it."),
        ("h3.what-a-mentor-does", "Sub-heading: What a mentor does", "What a mentor does"),
        ("p.volunteer-mentors-are-educators-engineers", "Paragraph: Volunteer mentors are educators, engineers, scientists, and ", "Volunteer mentors are educators, engineers, scientists, and graduates who give time to a student. The work is conversation more than instruction: what the job is actually like, which subjects matter, how an application is put together, and what to do when a plan does not survive contact with reality."),
        ("p.you-do-not-have-to", "Paragraph: You do not have to be in the room. Mentoring happens face to", "You do not have to be in the room. Mentoring happens face to face where the programmes run, and by phone or video from anywhere else."),
        ("h3.what-a-student-gets", "Sub-heading: What a student gets", "What a student gets"),
        ("p.member-students-are-matched-with", "Paragraph: Member students are matched with someone working in the fiel", "Member students are matched with someone working in the field they are curious about. Over a cohort, that becomes guidance on subject choices, university applications, and career direction — plus the thing no syllabus provides: a working adult who takes the question seriously."),
        ("p.mentorship-is-open-to-students", "Paragraph: Mentorship is open to students already in a foundation progr", "Mentorship is open to students already in a foundation programme — the Youth STEM School, the Science Fair, or a scholarship."),
        ("h2.the-mentorship-handbooks", "Heading: The mentorship handbooks", "The mentorship handbooks"),
        ("p.both-sides-of-the-pairing", "Paragraph: Both sides of the pairing get a handbook for the year. They ", "Both sides of the pairing get a handbook for the year. They are dated 10 September 2026 and prepared by Joshua Mutesasira in Kampala."),
        ("h2.could-you-be-the-person", "Heading: Could you be the person a student asks?", "Could you be the person a student asks?"),
        ("p.senior-civil-engineer", "Paragraph: Senior Civil Engineer", "Senior Civil Engineer"),
        ("p.a-senior-civil-engineer-specialising", "Paragraph: A Senior Civil Engineer specialising in dam safety and struc", "A Senior Civil Engineer specialising in dam safety and structural engineering. Rose brings professional practice and academic training together to help students see a concrete path from classroom STEM into engineering careers."),
        ("h2.where-it-runs", "Heading: Where it runs", "Where it runs"),
        ("p.scholarships-hands-on-stem-and", "Paragraph: Scholarships, hands-on STEM, and student-led innovation — me", "Scholarships, hands-on STEM, and student-led innovation — mentorship runs alongside all three."),
        ("p.teacher-training-equipment-access-and", "Paragraph: Teacher training, equipment access, and mentorship, as the p", "Teacher training, equipment access, and mentorship, as the programmes extend across the border."),
    ],
    "contact": [
        ("h2.reach-us-directly", "Heading: Reach us directly", "Reach us directly"),
        ("p.we-typically-reply-within-23", "Paragraph: We typically reply within 2–3 business days.", "We typically reply within 2–3 business days."),
        ("h3.program-operations", "Sub-heading: Program operations", "Program operations"),
        ("h2.send-a-message", "Heading: Send a message", "Send a message"),
        ("p.fill-out-the-form-and", "Paragraph: Fill out the form and your email app will open with the mess", "Fill out the form and your email app will open with the message ready to send."),
        ("h2.oklahoma-city-office", "Heading: Oklahoma City office", "Oklahoma City office"),
        ("h2.frequently-asked-questions", "Heading: Frequently asked questions", "Frequently asked questions"),
        ("p.answers-to-common-questions-about", "Paragraph: Answers to common questions about our foundation, programs, ", "Answers to common questions about our foundation, programs, and how to get involved."),
    ],
    "volunteers": [
        ("p.get-involved", "Paragraph: Get Involved", "Get Involved"),
        ("h1.volunteer-with-us", "Heading: Volunteer with us", "Volunteer with us"),
        ("p.help-us-put-stem-within", "Paragraph: Help us put STEM within reach of students who would not othe", "Help us put STEM within reach of students who would not otherwise get near it. Share a few hours, a skill, or a career’s worth of experience."),
        ("p.why-we-need-you", "Paragraph: Why we need you", "Why we need you"),
        ("h2.talent-is-everywhere-opportunity-is", "Heading: Talent is everywhere. Opportunity is not.", "Talent is everywhere. Opportunity is not."),
        ("p.across-uganda-and-south-sudan", "Paragraph: Across Uganda and South Sudan, students with real ability in", "Across Uganda and South Sudan, students with real ability in science, technology, engineering, and mathematics are held back by things that have nothing to do with ability: the cost of education, no laboratory to work in, no one to ask, and no professional network to show them what the work leads to."),
        ("p.volunteers-are-how-that-last", "Paragraph: Volunteers are how that last gap closes. An engineer who exp", "Volunteers are how that last gap closes. An engineer who explains what the job is actually like, a teacher who keeps a workshop moving, a graduate who answers a question about university applications — none of it requires a budget, and all of it changes what a student believes is available to them."),
        ("h2.what-it-means-to-volunteer", "Heading: What it means to volunteer", "What it means to volunteer"),
        ("p.it-is-not-a-lecture", "Paragraph: It is not a lecture series. Volunteering with the foundation", "It is not a lecture series. Volunteering with the foundation runs from mentoring one student through their next decision, to standing at the back of a science fair making sure twenty projects get set up on time."),
        ("p.you-do-not-have-to", "Paragraph: You do not have to be an engineer. Teachers, university stud", "You do not have to be an engineer. Teachers, university students, organisers, writers, and photographers all have a place here — and so does anyone willing to take a student’s question seriously."),
        ("h2.volunteer-roles", "Heading: Volunteer roles", "Volunteer roles"),
        ("p.two-ways-to-give-time", "Paragraph: Two ways to give time. Choose the one that fits where you ar", "Two ways to give time. Choose the one that fits where you are and how much of it you have."),
        ("p.not-sure-which-fits-pick", "Paragraph: Not sure which fits? Pick the area that interests you on the", "Not sure which fits? Pick the area that interests you on the form and the team will work the rest out with you."),
        ("h2.ready-to-make-an-impact", "Heading: Ready to make an impact?", "Ready to make an impact?"),
        ("p.one-form-a-couple-of", "Paragraph: One form, a couple of minutes. Everything after that is a co", "One form, a couple of minutes. Everything after that is a conversation."),
        ("h2.what-happens-after-you-apply", "Heading: What happens after you apply", "What happens after you apply"),
        ("h2.sign-up-to-volunteer", "Heading: Sign up to volunteer", "Sign up to volunteer"),
        ("p.tell-us-who-you-are", "Paragraph: Tell us who you are and where you would like to help. Fields", "Tell us who you are and where you would like to help. Fields marked * are required."),
        ("h2.another-way-to-help", "Heading: Another way to help", "Another way to help"),
        ("p.time-is-not-the-only", "Paragraph: Time is not the only thing the programmes run on.", "Time is not the only thing the programmes run on."),
        ("h3.partner-with-us", "Sub-heading: Partner with us", "Partner with us"),
        ("p.schools-universities-and-companies-work", "Paragraph: Schools, universities, and companies work with the foundatio", "Schools, universities, and companies work with the foundation on sessions, facilities, and placements. If your organisation could open a door, we would like to hear from you."),
        ("h3.support-a-student", "Sub-heading: Support a student", "Support a student"),
        ("p.scholarships-materials-and-travel-to", "Paragraph: Scholarships, materials, and travel to competitions are all ", "Scholarships, materials, and travel to competitions are all funded. A donation pays for the part of a student’s path that goodwill cannot."),
    ],
}


class Command(BaseCommand):
    help = "Create or update the editable copy on the hand-built pages."

    def add_arguments(self, parser):
        parser.add_argument("--page", help="Only this page.")
        parser.add_argument(
            "--overwrite",
            action="store_true",
            help="Also reset text that has been edited since it was seeded.",
        )

    def handle(self, *args, **options):
        only = options.get("page")
        overwrite = options["overwrite"]
        created_n = updated_n = kept_n = 0

        for page, entries in BLOCKS.items():
            if only and page != only:
                continue
            for key, label, value in entries:
                block, created = PageBlock.objects.get_or_create(
                    page=page, key=key,
                    defaults={"label": label, "value": value, "is_published": True},
                )
                if created:
                    created_n += 1
                    continue
                # Re-running must not silently undo someone's editing. The label
                # is ours to keep current; the text is theirs.
                block.label = label
                if overwrite:
                    block.value = value
                    updated_n += 1
                else:
                    kept_n += 1
                block.save(update_fields=["label", "value", "updated_at"])

        self.stdout.write(
            self.style.SUCCESS(
                f"{created_n} created, {updated_n} reset, {kept_n} left as edited; "
                f"{PageBlock.objects.count()} blocks total"
            )
        )
