# Generated by Django 5.2.5 on 2026-08-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal only. Never shown on the website.')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the notification email went out, if it did.', null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'contact message',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], db_index=True, default='subscribed', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Which page or form it came from.', max_length=100)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal only. Never shown on the website.')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the notification email went out, if it did.', null=True)),
                ('student_name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('class_stream', models.CharField(max_length=100, verbose_name='class / stream')),
                ('school', models.CharField(db_index=True, max_length=200)),
                ('district', models.CharField(db_index=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(blank=True, max_length=50)),
                ('guardian_contact', models.CharField(max_length=255, verbose_name='parent / guardian contact')),
                ('teacher_mentor', models.CharField(max_length=200)),
                ('head_teacher', models.CharField(blank=True, max_length=200)),
                ('project_title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('physical', 'Physical Sciences (Physics, Chemistry, Materials)'), ('life', 'Life & Environmental Sciences (Biology, Agriculture, Ecology, Public Health)'), ('engineering', 'Engineering & Technology (Devices, Mechanical/Electrical Systems, Renewable Energy)'), ('software', 'Computer Science & Software (Applications, Websites, Data Systems, AI Tools)'), ('innovation', 'Innovation & Entrepreneurship (New Products, Business Models with a Technical Core)'), ('community', 'Community & Social Impact Projects')], max_length=40)),
                ('project_type', models.CharField(blank=True, help_text='Comma-separated; the form allows several.', max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('team_size', models.CharField(blank=True, help_text='Individual or team project.', max_length=60)),
                ('summary', models.TextField(verbose_name='problem the student wants to work on')),
                ('declaration', models.BooleanField(default=False, help_text='Own original work, and any AI use to be declared in Section 12 of the workbook.')),
            ],
            options={
                'verbose_name': 'science fair registration',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('contacted', 'Contacted'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal only. Never shown on the website.')),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the notification email went out, if it did.', null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('interest', models.CharField(choices=[('mentorship', 'Mentorship'), ('event', 'Event organization'), ('tutoring', 'STEM tutoring'), ('outreach', 'Community outreach'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField(help_text='Why do you want to volunteer?')),
            ],
            options={
                'verbose_name': 'volunteer application',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
