# Generated by Django 5.2.5 on 2026-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan')], db_index=True, default='', help_text='Which office this belongs to. Blank until someone assigns it.', max_length=2),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan')], db_index=True, default='', help_text='Which office this belongs to. Blank until someone assigns it.', max_length=2),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan')], db_index=True, default='', help_text='Which office this belongs to. Blank until someone assigns it.', max_length=2),
        ),
    ]
