# Generated by Django 5.2.5 on 2026-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_contactmessage_country_projectproposal_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='', help_text='Which office this belongs to. Blank until someone assigns it.', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='', help_text='Which office this belongs to. Blank until someone assigns it.', max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='', help_text='Which office this belongs to. Blank until someone assigns it.', max_length=2),
        ),
    ]
