# Generated by Django 5.2.5 on 2026-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_contactmessage_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text="Which office's list this address belongs to.", max_length=2),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='', help_text='Blank until somebody assigns this to an office.', max_length=2),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='', help_text='Blank until somebody assigns this to an office.', max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='', help_text='Blank until somebody assigns this to an office.', max_length=2),
        ),
    ]
