# Generated by Django 5.2.5 on 2026-08-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_record_office'),
        ('submissions', '0004_newslettersubscriber_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Which office is handling this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.office'),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Which office is handling this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.office'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='office',
            field=models.ForeignKey(blank=True, help_text='Which office is handling this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.office'),
        ),
    ]
