# Generated by Django 5.2.5 on 2026-08-30 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_newslettersubscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='student_phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[\\d\\s()-]{6,20}$')]),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='summary',
            field=models.TextField(max_length=4000, verbose_name='problem the student wants to work on'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='message',
            field=models.TextField(help_text='Why do you want to volunteer?', max_length=4000),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[\\d\\s()-]{6,20}$')]),
        ),
    ]
