# Generated by Django 5.2.5 on 2026-09-14 13:57

from django.db import migrations, models


def carry_across(apps, schema_editor):
    """Anybody already recognised as a team member in the volunteers group.

    Empty on the server this was written against — checked, not assumed — but
    a migration that only works against one snapshot of the data is a migration
    that loses somebody's record on a copy of the database somebody else holds.
    """
    TeamMember = apps.get_model("content_cms", "TeamMember")
    Volunteer = apps.get_model("submissions", "VolunteerApplication")
    for member in TeamMember.objects.filter(group="volunteers"):
        Volunteer.objects.create(
            name=member.name,
            email=member.email or "",
            role=member.role or "",
            bio=member.bio or "",
            photo=member.image or "",
            alt=member.alt or "",
            linkedin=member.linkedin or "",
            order=member.order or 0,
            is_published=member.is_published,
            country=member.country or "",
            status="closed",
        )
    TeamMember.objects.filter(group="volunteers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("content_cms", "0001_initial"),
        ('submissions', '0007_alter_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'volunteer'},
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='alt',
            field=models.CharField(blank=True, help_text='Describes the photograph.', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='bio',
            field=models.TextField(blank=True, help_text='Why they are recognised.'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Named on the volunteers page.'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first on the page.'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='photo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='role',
            field=models.CharField(blank=True, help_text='What they did, e.g. Science Fair judge.', max_length=150),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='interest',
            field=models.CharField(blank=True, choices=[('mentorship', 'Mentorship'), ('event', 'Event organization'), ('tutoring', 'STEM tutoring'), ('outreach', 'Community outreach'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='message',
            field=models.TextField(blank=True, help_text='Why do you want to volunteer?', max_length=4000),
        ),
        migrations.RunPython(carry_across, migrations.RunPython.noop),
    ]
