# Generated by Django 5.2.5 on 2026-08-30 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-received_on', '-created_at']},
        ),
        migrations.AddField(
            model_name='donation',
            name='designation',
            field=models.CharField(blank=True, help_text='What the gift is for. Blank means unrestricted.', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='gift_type',
            field=models.CharField(choices=[('one_off', 'One-off gift'), ('recurring', 'Recurring gift'), ('pledge', 'Pledge'), ('in_kind', 'In kind'), ('grant', 'Grant')], db_index=True, default='one_off', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank', 'Bank transfer'), ('mobile', 'Mobile money'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('in_kind', 'In kind'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='receipt_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent'), ('not_required', 'Not required')], default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='received_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='source',
            field=models.CharField(choices=[('online', 'Online (Stripe)'), ('offline', 'Recorded by hand')], db_index=True, default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('pledged', 'Pledged'), ('received', 'Received')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
