# Generated by Django 5.2.5 on 2026-08-29 06:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0005_record_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(help_text='One or two sentences. This is the card on /careers.')),
                ('description', models.TextField(blank=True, help_text='The full description. Markdown.')),
                ('responsibilities', models.TextField(blank=True, help_text='What the role involves. One per line.')),
                ('requirements', models.TextField(blank=True, help_text='What is required. One per line.')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
                ('is_open', models.BooleanField(db_index=True, default=True, help_text='Open postings appear on the careers page.')),
                ('posted_on', models.DateField(default=django.utils.timezone.localdate)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='operations.office')),
            ],
            options={
                'ordering': ['order', '-posted_on', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posting_title', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('cover_letter', models.TextField(blank=True)),
                ('cv', models.CharField(blank=True, help_text="The applicant's CV, in object storage.", max_length=500)),
                ('stage', models.CharField(choices=[('new', 'New'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Not taken forward'), ('withdrawn', 'Withdrawn')], db_index=True, default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal. Never shown to the applicant.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_decisions', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
