# Generated by Django 5.2.5 on 2026-08-28 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0005_record_office'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this document is for.')),
                ('category', models.CharField(choices=[('handbook', 'Handbook'), ('policy', 'Policy'), ('form', 'Form'), ('report', 'Report'), ('template', 'Template'), ('governance', 'Governance'), ('finance', 'Finance'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Keeps it out of the way without destroying it.')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Published on the website. Leave off for anything internal.')),
                ('notes', models.TextField(blank=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='operations.office')),
                ('owner', models.ForeignKey(blank=True, help_text='Who is responsible for keeping this current.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(help_text='How this edition is referred to, e.g. 2026/27 or v2.1.', max_length=60)),
                ('file', models.FileField(blank=True, upload_to='documents/')),
                ('external_url', models.URLField(blank=True, help_text='If the file lives in Drive or OneDrive instead.', max_length=500)),
                ('effective_date', models.DateField(blank=True, help_text='When this edition took effect.', null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='The edition in force. Only one per document.')),
                ('summary', models.TextField(blank=True, help_text='What changed in this edition.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_editions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='one_current_edition_per_document'), models.UniqueConstraint(fields=('document', 'version'), name='one_row_per_document_version')],
            },
        ),
    ]
