# Generated by Django 5.2.5 on 2026-08-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentedition',
            name='preview_image',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='documentedition',
            name='preview_source',
            field=models.CharField(blank=True, editable=False, max_length=500),
        ),
    ]
