# Generated by Django 5.2.5 on 2026-08-28 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content_cms', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. 2026/27', max_length=120, unique=True)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-starts_on', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('guardian_contact', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, db_index=True, max_length=200)),
                ('class_stream', models.CharField(blank=True, max_length=100, verbose_name='class / stream')),
                ('district', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('XX', 'Other')], max_length=2)),
                ('interests', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, help_text='e.g. Senior Civil Engineer', max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('expertise', models.CharField(blank=True, help_text='Comma-separated fields they can speak to.', max_length=300)),
                ('mode', models.CharField(choices=[('in_person', 'In person'), ('remote', 'Remote'), ('both', 'Either')], default='both', max_length=20)),
                ('country', models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('XX', 'Other')], max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, help_text='The volunteer application this mentor came from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='submissions.volunteerapplication')),
                ('team_member', models.OneToOneField(blank=True, help_text='Link if this mentor is also published on the team page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_record', to='content_cms.teammember')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScienceFairProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('physical', 'Physical Sciences (Physics, Chemistry, Materials)'), ('life', 'Life & Environmental Sciences (Biology, Agriculture, Ecology, Public Health)'), ('engineering', 'Engineering & Technology (Devices, Mechanical/Electrical Systems, Renewable Energy)'), ('software', 'Computer Science & Software (Applications, Websites, Data Systems, AI Tools)'), ('innovation', 'Innovation & Entrepreneurship (New Products, Business Models with a Technical Core)'), ('community', 'Community & Social Impact Projects')], max_length=40)),
                ('school', models.CharField(db_index=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(choices=[('handbook_released', '1. Handbook released to schools'), ('project_chosen', '2. Choose a project, find a mentor'), ('proposal_submitted', '3. Submit your proposal'), ('under_review', '4. Review and feedback'), ('research_and_build', '5. Research and build'), ('school_fair', '6. School-level fair'), ('regional_fair', '7. Regional fair'), ('national_fair', '8. National fair')], db_index=True, default='proposal_submitted', max_length=30)),
                ('teacher_mentor', models.CharField(blank=True, max_length=200)),
                ('review_score', models.PositiveSmallIntegerField(blank=True, help_text='Out of 100, from the review stage.', null=True)),
                ('review_feedback', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='programmes.cohort')),
                ('registration', models.OneToOneField(blank=True, help_text='The online registration this project came from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='submissions.projectproposal')),
                ('students', models.ManyToManyField(blank=True, related_name='projects', to='programmes.mentee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MentorshipPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('ended', 'Ended early')], db_index=True, default='proposed', max_length=20)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairings', to='programmes.cohort')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairings', to='programmes.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pairings', to='programmes.mentor')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('mentor', 'mentee', 'cohort'), name='unique_pairing_per_cohort')],
            },
        ),
    ]
