# Generated by Django 5.2.5 on 2026-08-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencefairproject',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('XX', 'Other')], db_index=True, default='', max_length=2),
        ),
    ]
