# Generated by Django 5.2.5 on 2026-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_sciencefairproject_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States'), ('XX', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States'), ('XX', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sciencefairproject',
            name='country',
            field=models.CharField(blank=True, choices=[('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States'), ('XX', 'Other')], db_index=True, default='', max_length=2),
        ),
    ]
