# Generated by Django 5.2.5 on 2026-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_alter_mentee_country_alter_mentor_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], max_length=2),
        ),
        migrations.AlterField(
            model_name='sciencefairproject',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='', max_length=2),
        ),
    ]
