# Generated by Django 5.2.5 on 2026-08-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_record_office'),
        ('programmes', '0004_alter_mentee_country_alter_mentor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.office'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.office'),
        ),
    ]
