# Generated by Django 5.2.5 on 2026-08-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_mentee_office_mentor_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sciencefairproject',
            name='stage',
            field=models.CharField(choices=[('handbook_released', '1. Handbook released to schools'), ('project_chosen', '2. Choose a project, find a mentor'), ('proposal_submitted', '3. Submit your proposal'), ('under_review', '4. Review and feedback'), ('research_and_build', '5. Research and build'), ('school_fair', '6. School-level fair'), ('regional_fair', '7. Regional fair'), ('national_fair', '8. National fair'), ('completed', '9. Completed'), ('withdrawn', 'Withdrawn')], db_index=True, default='proposal_submitted', max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('placement', 'Placement at a fair'), ('prize', 'Prize'), ('scholarship', 'Scholarship'), ('equipment', 'Equipment'), ('certificate', 'Certificate'), ('mentorship', 'Mentorship place'), ('other', 'Other')], db_index=True, default='prize', max_length=30)),
                ('title', models.CharField(help_text='e.g. First place, regional fair.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='If it carries money. Leave blank if it does not.', max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, help_text='Required when there is an amount.', max_length=3)),
                ('awarded_on', models.DateField(blank=True, null=True)),
                ('awarded_by', models.CharField(blank=True, help_text='Who gave it — the Foundation, a partner, a sponsor.', max_length=200)),
                ('is_delivered', models.BooleanField(db_index=True, default=False, help_text='Whether the student has actually received it.')),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='programmes.sciencefairproject')),
            ],
            options={
                'ordering': ['-awarded_on', '-created_at'],
            },
        ),
    ]
