# Generated by Django 5.2.5 on 2026-08-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='cover_image',
            field=models.CharField(blank=True, help_text='Optional cover image, shown in the email above the link.', max_length=500),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='issue_label',
            field=models.CharField(blank=True, help_text='Which issue this is, e.g. August 2026.', max_length=120),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='pdf',
            field=models.CharField(blank=True, help_text='The newsletter PDF. Uploaded, or a path under /public.', max_length=500),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='published_on',
            field=models.DateField(blank=True, help_text='The issue date.', null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(blank=True, help_text='Optional short note in the email, above the link. Markdown.'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='preheader',
            field=models.CharField(blank=True, help_text='The grey line after the subject in an inbox. Left blank, the first line of the note is used.', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(help_text='The email subject line.', max_length=200),
        ),
    ]
