# Generated by Django 5.2.5 on 2026-08-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_newsletter_preview_image_newsletter_preview_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text="Show this issue on the website's newsletters page."),
        ),
    ]
