# Generated by Django 5.2.5 on 2026-08-28 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_id', models.SlugField(help_text='e.g. 2026', max_length=60, unique=True)),
                ('label', models.CharField(help_text='Issue line as printed on the cover, e.g. 11/2026.', max_length=60)),
                ('name', models.CharField(help_text='How the issue is referred to in prose.', max_length=120)),
                ('status', models.CharField(choices=[('published', 'Published'), ('in-production', 'In production')], default='in-production', max_length=20)),
                ('cover', models.CharField(blank=True, max_length=300)),
                ('cover_upload', models.ImageField(blank=True, upload_to='magazine/')),
                ('cover_alt', models.CharField(blank=True, max_length=300)),
                ('wrap', models.CharField(blank=True, help_text='Full wrap: back cover, spine, front.', max_length=300)),
                ('wrap_alt', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('file_href', models.CharField(blank=True, max_length=300)),
                ('file_upload', models.FileField(blank=True, upload_to='magazine/')),
                ('file_filename', models.CharField(blank=True, help_text='Filename the browser saves it as.', max_length=200)),
                ('file_size', models.CharField(blank=True, max_length=40)),
                ('file_contains', models.CharField(blank=True, choices=[('Full issue', 'Full issue'), ('Cover', 'Cover')], help_text='What the file actually holds, so the page never overstates it.', max_length=20)),
                ('epigraph_quote', models.TextField(blank=True)),
                ('epigraph_attribution', models.CharField(blank=True, max_length=200)),
                ('epigraph_source', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower sorts first; the first entry is featured.')),
            ],
            options={
                'ordering': ['order', '-issue_id'],
            },
        ),
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True, help_text='The date the story is about.')),
                ('date_label', models.CharField(blank=True, help_text='Display date. Derived if left blank.', max_length=60)),
                ('reading_time', models.CharField(blank=True, max_length=40)),
                ('excerpt', models.TextField(help_text='One-sentence standfirst, used on the card and under the headline.')),
                ('body', models.TextField(help_text='Markdown.')),
                ('image', models.CharField(blank=True, help_text='Path under /public, or an uploaded file below.', max_length=300)),
                ('image_upload', models.ImageField(blank=True, upload_to='news/')),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'news stories',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('group', models.CharField(choices=[('leadership', 'Leadership'), ('mentors', 'Mentors')], db_index=True, default='leadership', max_length=20)),
                ('image', models.CharField(blank=True, help_text='Path under /public, or an uploaded file below.', max_length=300)),
                ('image_upload', models.ImageField(blank=True, upload_to='team/')),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('focus', models.CharField(blank=True, help_text="CSS object-position, e.g. 'center 20%'.", max_length=60)),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MagazineStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blurb', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='content_cms.magazineissue')),
            ],
            options={
                'verbose_name_plural': 'magazine stories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Feather icon name.', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content_cms.newsstory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(blank=True, max_length=300)),
                ('upload', models.ImageField(blank=True, upload_to='news/gallery/')),
                ('alt', models.CharField(max_length=300)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content_cms.newsstory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
