# Generated by Django 5.2.5 on 2026-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineissue',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2),
        ),
        migrations.AddField(
            model_name='newsstory',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2),
        ),
        migrations.AddField(
            model_name='teammember',
            name='country',
            field=models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2),
        ),
    ]
