# Generated by Django 5.2.5 on 2026-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0002_magazineissue_country_newsstory_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, help_text="e.g. + for '120+'.", max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
                ('note', models.TextField(blank=True, help_text='Internal: where this figure comes from.')),
            ],
            options={
                'verbose_name': 'home page statistic',
                'ordering': ['order', 'id'],
            },
        ),
    ]
