# Generated by Django 5.2.5 on 2026-08-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0003_sitestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='The short line under the title on the card.', max_length=200)),
                ('summary', models.TextField(help_text="One or two sentences. This is the card's body.")),
                ('href', models.CharField(blank=True, help_text='Where the card links. Leave blank if the programme has no page of its own yet.', max_length=200)),
                ('image', models.CharField(blank=True, help_text='Path under /public, or upload one below.', max_length=300)),
                ('image_upload', models.ImageField(blank=True, upload_to='programmes/')),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(blank=True, help_text='Icon name, e.g. users, globe, book-open, award.', max_length=60)),
                ('pathway_stage', models.CharField(blank=True, help_text='Its step in the pathway, e.g. Inspire. Blank keeps it out of the pathway strip.', max_length=60)),
                ('pathway_label', models.CharField(blank=True, help_text='Name shown in the pathway strip. Defaults to the name.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(db_index=True, help_text='Which page, e.g. about, uganda, impact.', max_length=80)),
                ('key', models.CharField(help_text='Which piece of that page, e.g. hero.heading.', max_length=120)),
                ('value', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, help_text='What this is, in plain words, for whoever edits it.', max_length=200)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Unpublished falls back to the built-in text.')),
                ('country', models.CharField(blank=True, choices=[('GL', 'Global — all countries'), ('UG', 'Uganda'), ('SS', 'South Sudan'), ('US', 'United States')], db_index=True, default='GL', help_text='Which office this belongs to. Choose Global when it belongs to the Foundation as a whole rather than one country.', max_length=2)),
            ],
            options={
                'ordering': ['page', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='one_block_per_page_key')],
            },
        ),
    ]
