# Generated by Django 5.2.5 on 2026-08-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0004_programme_pageblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='group',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('mentors', 'Mentors'), ('volunteers', 'Outstanding volunteers')], db_index=True, default='leadership', max_length=20),
        ),
    ]
