# Generated by Django 5.2.5 on 2026-08-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0005_alter_teammember_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazineissue',
            options={'ordering': ['order', models.OrderBy(models.F('published_on'), descending=True, nulls_last=True), '-issue_id']},
        ),
        migrations.AddField(
            model_name='magazineissue',
            name='published_on',
            field=models.DateField(blank=True, help_text='The issue date. The most recent issue leads the magazine page.', null=True),
        ),
        migrations.AlterField(
            model_name='magazineissue',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Leave at 0 to let the date decide. Raise it to push an issue down the page.'),
        ),
    ]
