# Generated by Django 5.2.5 on 2026-09-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0009_teammember_role_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='group',
            field=models.CharField(choices=[('leadership', 'Leadership'), ('mentors', 'Mentors')], db_index=True, default='leadership', max_length=20),
        ),
    ]
