# Generated by Django 5.2.5 on 2026-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0010_alter_teammember_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='board',
            field=models.CharField(blank=True, db_index=True, help_text='The page that records activity under this programme.', max_length=120),
        ),
    ]
