# Generated by Django 5.2.5 on 2026-09-14 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def match_existing(apps, schema_editor):
    """Join the colleagues already here to the accounts they sign in with.

    By email first, which is exact. Then by full name, because two of the five
    accounts carry no address at all — they were created for people who had
    not been given a mailbox yet. A name match is only accepted when it is
    unique on both sides; anything ambiguous is left for a person to link,
    since guessing wrong here attaches somebody's access to somebody else.
    """
    TeamMember = apps.get_model("content_cms", "TeamMember")
    User = apps.get_model("auth", "User")

    taken = set()

    def claim(member, user):
        if user.pk in taken:
            return False
        member.account_id = user.pk
        member.save(update_fields=["account"])
        taken.add(user.pk)
        return True

    staff = list(User.objects.filter(is_staff=True))
    members = list(TeamMember.objects.all())

    for member in members:
        if not member.email:
            continue
        hit = [u for u in staff if u.email and u.email.lower() == member.email.lower()]
        if len(hit) == 1:
            claim(member, hit[0])

    for member in members:
        if member.account_id:
            continue
        name = member.name.strip().lower()
        hit = [
            u for u in staff
            if u.pk not in taken
            and f"{u.first_name} {u.last_name}".strip().lower() == name
        ]
        if len(hit) == 1:
            claim(member, hit[0])


class Migration(migrations.Migration):

    dependencies = [
        ('content_cms', '0011_programme_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='account',
            field=models.OneToOneField(blank=True, help_text='The dashboard account this person signs in with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(match_existing, migrations.RunPython.noop),
    ]
